apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springbootapp
    app.kubernetes.io/managed-by: Helm
  name: springbootapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: springbootapp
  type: LoadBalancer
status:
  loadBalancer: {}
